# Generated by Django 4.2.2 on 2023-11-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_blog_options_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lastname",
            field=models.CharField(default="lastname", max_length=200),
        ),
    ]
