# Generated by Django 4.2.2 on 2023-11-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_blog_title_delete_topic"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="UserModel",),
    ]
